services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    networks:
      - app-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-net
    depends_on:
      - mongo

  website:
    build: ./CarPark
    environment:
      - MONGODB_URL=mongodb://root:example@localhost:27018
      - MONGODB_DATABASE_NAME=carParkDB
    networks:
      - app-net
    depends_on:
      - mongo

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - website
     
networks:
  app-net:
    driver: bridge